---
- name: Configure Base Webserver, Firewall, SSH, Sudoers, Cron and Large Files
  hosts: all
  become: true

  pre_tasks:
    - name: Ansible ping pre test
      ansible.builtin.ping:

  roles:
    - config

