---
- name: Stop and disable httpd service
  ansible.builtin.service:
    name: httpd
    state: stopped
    enabled: false

- name: Stop and disable firewalld service
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: false

- name: Remove HTTP service from firewalld
  ansible.builtin.firewalld:
    service: http
    permanent: true
    state: disabled
    immediate: true
  notify: Reload firewalld

- name: Remove SSH service from firewalld
  ansible.builtin.firewalld:
    service: ssh
    permanent: true
    state: disabled
    immediate: true
  notify: Reload firewalld

- name: Remove web content files
  ansible.builtin.file:
    path: "{{ web_root }}"
    state: absent
    recurse: true

- name: Uninstall epel-release, httpd and firewalld packages
  ansible.builtin.dnf:
    name:
      - httpd
      - firewalld
    state: absent

- name: Remove sudoers file for user1
  ansible.builtin.file:
    path: "/etc/sudoers.d/{{ user_name }}"
    state: absent

- name: Remove log-trimming script
  ansible.builtin.file:
    path: /usr/local/bin/trim-logs.sh
    state: absent

- name: Remove cron job for log trimming
  ansible.builtin.file:
    path: /etc/cron.d/trim-logs
    state: absent

- name: Remove large files directory and its contents
  ansible.builtin.file:
    path: "{{ large_files_dir }}"
    state: absent
    recurse: true
