---
- name: Remove web content files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ web_root }}/index.html"
    - "{{ web_root }}/page2.html"

- name: Uninstall epel-release, httpd and firewalld packages
  ansible.builtin.dnf:
    name:
      - httpd
      - firewalld
    state: absent

- name: Remove log-trimming script
  ansible.builtin.file:
    path: /usr/local/bin/trim-logs.sh
    state: absent

- name: Remove cron job for log trimming
  ansible.builtin.file:
    path: /etc/cron.d/trim-logs
    state: absent

- name: Remove large files directory and its contents
  ansible.builtin.file:
    path: "{{ large_files_dir }}"
    state: absent
    recurse: true
