- name: Install HTTPD and firewalld
  tags: install
  ansible.builtin.dnf:
    name:
      - httpd
      - firewalld
    state: present

- name: Setup Webserver
  tags: install
  ansible.builtin.import_tasks: web.yml

# - name: Setup Firewalld
#   tags: install
#   ansible.builtin.import_tasks: firewalld.yml

# - name: Setup Access
#   ansible.builtin.import_tasks: access.yml

- name: Generate files
  tags: install
  ansible.builtin.import_tasks: files.yml

- name: Revert env
  tags: destroy
  ansible.builtin.import_tasks: destroy.yml
