- name: Install HTTPD and firewalld
  tags: install
  ansible.builtin.dnf:
    name:
      - httpd
      - firewalld
    state: present

- name: Setup Webserver
  tags: install
  ansible.builtin.import_tasks: web.yml

- name: Simulate the long-running operation
  tags: install
  ansible.builtin.command: /bin/sleep 60
  async: 90
  poll: 20

- name: Generate files
  tags: install
  ansible.builtin.import_tasks: files.yml

- name: Revert env
  tags: destroy
  ansible.builtin.import_tasks: destroy.yml
